package:
    type:           yii2-extension
    name:           yii2-asset-jquery-resizable-columns
    title:          Yii2 asset for jQuery resizable columns
    headline:       Yii2 jquery-resizable-columns
    keywords:       yii2, asset, jquery, resizable, columns
    namespace:      hiqdev\yii2\assets\JqueryResizableColumns
    description:    |
        This package is Yii2 asset bundle for [jquery-resizable-columns](https://github.com/dobtco/jquery-resizable-columns).

